app:
  project_name: async-python-sprint-4
  description: sprint 4 in Async Python Course in Yandex Praktikum
  version: 0.1.0
  api_doc_prefix: /api/v1
  host: 0.0.0.0
  port: 8000
  debug: true
  blacklist:
    - 10.0.0.0/8
    - 203.0.113.0/24
    - 198.51.100.0/24

postgres:
  host: localhost
  port: 5432
  dbname: sprint_4
  user: sprint_4
  password: sprint_4
